2024-05-30 09:39:16,436 INFO: Microblog startup [in /home/vaddi/Desktop/project repos/flask-microblog/app/__init__.py:94]
2024-05-30 09:39:16,904 INFO: Microblog startup [in /home/vaddi/Desktop/project repos/flask-microblog/app/__init__.py:94]
2024-05-30 12:35:04,689 INFO: Microblog startup [in /home/vaddi/Desktop/project repos/flask-microblog/app/__init__.py:94]
2024-05-30 12:35:05,483 INFO: Microblog startup [in /home/vaddi/Desktop/project repos/flask-microblog/app/__init__.py:94]
2024-05-30 13:43:47,114 INFO: Microblog startup [in /home/vaddi/Desktop/project repos/flask-microblog/app/__init__.py:94]
2024-05-30 13:44:25,935 INFO: Microblog startup [in /home/vaddi/Desktop/project repos/flask-microblog/app/__init__.py:94]
2024-05-30 13:44:45,444 INFO: Microblog startup [in /home/vaddi/Desktop/project repos/flask-microblog/app/__init__.py:94]
2024-05-30 13:44:53,890 INFO: Microblog startup [in /home/vaddi/Desktop/project repos/flask-microblog/app/__init__.py:94]
2024-05-30 14:49:49,320 INFO: Microblog startup [in /home/vaddi/Desktop/project repos/flask-microblog/app/__init__.py:94]
2024-05-30 15:00:50,188 INFO: Microblog startup [in /home/vaddi/Desktop/project repos/flask-microblog/app/__init__.py:94]
2024-05-30 15:08:55,362 INFO: Microblog startup [in /home/vaddi/Desktop/project repos/flask-microblog/app/__init__.py:94]
2024-05-30 15:08:56,131 INFO: Microblog startup [in /home/vaddi/Desktop/project repos/flask-microblog/app/__init__.py:94]
2024-05-30 15:13:14,179 INFO: Microblog startup [in /home/vaddi/Desktop/project repos/flask-microblog/app/__init__.py:94]
2024-05-30 15:13:16,148 INFO: Microblog startup [in /home/vaddi/Desktop/project repos/flask-microblog/app/__init__.py:94]
2024-05-30 15:13:19,299 INFO: Microblog startup [in /home/vaddi/Desktop/project repos/flask-microblog/app/__init__.py:94]
2024-05-30 15:13:21,250 INFO: Microblog startup [in /home/vaddi/Desktop/project repos/flask-microblog/app/__init__.py:94]
2024-05-30 15:13:23,641 INFO: Microblog startup [in /home/vaddi/Desktop/project repos/flask-microblog/app/__init__.py:94]
2024-05-30 15:13:25,745 INFO: Microblog startup [in /home/vaddi/Desktop/project repos/flask-microblog/app/__init__.py:94]
2024-05-30 15:13:28,886 INFO: Microblog startup [in /home/vaddi/Desktop/project repos/flask-microblog/app/__init__.py:94]
2024-05-30 15:13:44,805 INFO: Microblog startup [in /home/vaddi/Desktop/project repos/flask-microblog/app/__init__.py:94]
2024-05-30 15:24:10,431 INFO: Microblog startup [in /home/vaddi/Desktop/project repos/flask-microblog/app/__init__.py:94]
2024-05-30 15:27:42,065 INFO: Microblog startup [in /home/vaddi/Desktop/project repos/flask-microblog/app/__init__.py:94]
2024-05-30 15:27:45,030 INFO: Microblog startup [in /home/vaddi/Desktop/project repos/flask-microblog/app/__init__.py:94]
2024-05-30 15:31:24,626 INFO: Microblog startup [in /home/vaddi/Desktop/project repos/flask-microblog/app/__init__.py:94]
2024-05-30 15:31:25,168 INFO: Microblog startup [in /home/vaddi/Desktop/project repos/flask-microblog/app/__init__.py:94]
2024-05-30 15:31:41,881 INFO: Microblog startup [in /home/vaddi/Desktop/project repos/flask-microblog/app/__init__.py:94]
2024-05-30 15:33:16,988 INFO: Microblog startup [in /home/vaddi/Desktop/project repos/flask-microblog/app/__init__.py:94]
2024-05-30 15:33:18,971 INFO: Microblog startup [in /home/vaddi/Desktop/project repos/flask-microblog/app/__init__.py:94]
2024-05-30 15:33:21,919 INFO: Microblog startup [in /home/vaddi/Desktop/project repos/flask-microblog/app/__init__.py:94]
2024-05-30 15:33:23,969 INFO: Microblog startup [in /home/vaddi/Desktop/project repos/flask-microblog/app/__init__.py:94]
2024-05-30 15:34:09,383 INFO: Microblog startup [in /home/vaddi/Desktop/project repos/flask-microblog/app/__init__.py:94]
2024-05-30 15:34:09,435 ERROR: Unhandled exception [in /home/vaddi/Desktop/project repos/flask-microblog/app/tasks.py:46]
Traceback (most recent call last):
  File "/home/vaddi/Desktop/project repos/flask-microblog/app/tasks.py", line 32, in export_posts
    total_posts = user.posts.count()
                  ^^^^^^^^^^
AttributeError: 'User' object has no attribute 'posts'. Did you mean: 'post'?
2024-05-30 15:35:58,341 INFO: Microblog startup [in /home/vaddi/Desktop/project repos/flask-microblog/app/__init__.py:94]
2024-05-30 15:36:00,246 INFO: Microblog startup [in /home/vaddi/Desktop/project repos/flask-microblog/app/__init__.py:94]
2024-05-30 15:36:02,185 INFO: Microblog startup [in /home/vaddi/Desktop/project repos/flask-microblog/app/__init__.py:94]
2024-05-30 15:36:33,057 INFO: Microblog startup [in /home/vaddi/Desktop/project repos/flask-microblog/app/__init__.py:94]
2024-05-30 15:36:38,281 ERROR: Unhandled exception [in /home/vaddi/Desktop/project repos/flask-microblog/app/tasks.py:46]
Traceback (most recent call last):
  File "/home/vaddi/Desktop/project repos/flask-microblog/app/tasks.py", line 39, in export_posts
    send_email('Your blog posts',
  File "/home/vaddi/Desktop/project repos/flask-microblog/app/email.py", line 20, in send_email
    mail.send(msg)
  File "/home/vaddi/Desktop/project repos/flask-microblog/venv/lib/python3.12/site-packages/flask_mail/__init__.py", line 540, in send
    message.send(connection)
  File "/home/vaddi/Desktop/project repos/flask-microblog/venv/lib/python3.12/site-packages/flask_mail/__init__.py", line 482, in send
    connection.send(self)
  File "/home/vaddi/Desktop/project repos/flask-microblog/venv/lib/python3.12/site-packages/flask_mail/__init__.py", line 177, in send
    self.host.sendmail(
  File "/usr/lib/python3.12/smtplib.py", line 876, in sendmail
    raise SMTPSenderRefused(code, resp, from_addr)
smtplib.SMTPSenderRefused: (530, b'5.7.0 Authentication Required. For more information, go to\n5.7.0  https://support.google.com/mail/?p=WantAuthError ffacd0b85a97d-35da8623000sm3105710f8f.9 - gsmtp', 'vijayzvaddi@gmail.com')
2024-05-30 15:38:15,985 INFO: Microblog startup [in /home/vaddi/Desktop/project repos/flask-microblog/app/__init__.py:94]
2024-05-30 15:38:16,720 INFO: Microblog startup [in /home/vaddi/Desktop/project repos/flask-microblog/app/__init__.py:94]
2024-05-30 15:38:30,673 INFO: Microblog startup [in /home/vaddi/Desktop/project repos/flask-microblog/app/__init__.py:94]
2024-05-30 15:38:35,904 ERROR: Unhandled exception [in /home/vaddi/Desktop/project repos/flask-microblog/app/tasks.py:46]
Traceback (most recent call last):
  File "/home/vaddi/Desktop/project repos/flask-microblog/app/tasks.py", line 39, in export_posts
    send_email('Your blog posts',
  File "/home/vaddi/Desktop/project repos/flask-microblog/app/email.py", line 20, in send_email
    mail.send(msg)
  File "/home/vaddi/Desktop/project repos/flask-microblog/venv/lib/python3.12/site-packages/flask_mail/__init__.py", line 540, in send
    message.send(connection)
  File "/home/vaddi/Desktop/project repos/flask-microblog/venv/lib/python3.12/site-packages/flask_mail/__init__.py", line 482, in send
    connection.send(self)
  File "/home/vaddi/Desktop/project repos/flask-microblog/venv/lib/python3.12/site-packages/flask_mail/__init__.py", line 177, in send
    self.host.sendmail(
  File "/usr/lib/python3.12/smtplib.py", line 876, in sendmail
    raise SMTPSenderRefused(code, resp, from_addr)
smtplib.SMTPSenderRefused: (530, b'5.7.0 Authentication Required. For more information, go to\n5.7.0  https://support.google.com/mail/?p=WantAuthError ffacd0b85a97d-3557dcf03e3sm17578955f8f.101 - gsmtp', 'vijayzvaddi@gmail.com')
2024-05-30 15:40:02,763 INFO: Microblog startup [in /home/vaddi/Desktop/project repos/flask-microblog/app/__init__.py:94]
2024-05-30 15:40:03,519 INFO: Microblog startup [in /home/vaddi/Desktop/project repos/flask-microblog/app/__init__.py:94]
2024-05-30 15:40:33,146 INFO: Microblog startup [in /home/vaddi/Desktop/project repos/flask-microblog/app/__init__.py:94]
2024-05-30 15:40:38,403 ERROR: Unhandled exception [in /home/vaddi/Desktop/project repos/flask-microblog/app/tasks.py:46]
Traceback (most recent call last):
  File "/home/vaddi/Desktop/project repos/flask-microblog/app/tasks.py", line 39, in export_posts
    send_email('Your blog posts',
  File "/home/vaddi/Desktop/project repos/flask-microblog/app/email.py", line 20, in send_email
    mail.send(msg)
  File "/home/vaddi/Desktop/project repos/flask-microblog/venv/lib/python3.12/site-packages/flask_mail/__init__.py", line 540, in send
    message.send(connection)
  File "/home/vaddi/Desktop/project repos/flask-microblog/venv/lib/python3.12/site-packages/flask_mail/__init__.py", line 482, in send
    connection.send(self)
  File "/home/vaddi/Desktop/project repos/flask-microblog/venv/lib/python3.12/site-packages/flask_mail/__init__.py", line 177, in send
    self.host.sendmail(
  File "/usr/lib/python3.12/smtplib.py", line 876, in sendmail
    raise SMTPSenderRefused(code, resp, from_addr)
smtplib.SMTPSenderRefused: (530, b'5.7.0 Authentication Required. For more information, go to\n5.7.0  https://support.google.com/mail/?p=WantAuthError 5b1f17b1804b1-4212705530bsm27061005e9.5 - gsmtp', 'vijayzvaddi@gmail.com')
2024-05-30 15:41:01,543 INFO: Microblog startup [in /home/vaddi/Desktop/project repos/flask-microblog/app/__init__.py:94]
